package com.example.evcharging;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.Objects;

public class Signup extends AppCompatActivity {
    private EditText enterEmail;
    private EditText password;
    private EditText firstName;
    private EditText lastName;
    private EditText mobileNumber;

    private FirebaseAuth mAuth;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_signup);

        mAuth = FirebaseAuth.getInstance();
        enterEmail = findViewById(R.id.enterEmails);
        password = findViewById(R.id.passwords);
        firstName = findViewById(R.id.firstName);
        lastName = findViewById(R.id.lastName);
        mobileNumber = findViewById(R.id.mobileNumber);
        Button btnSignup = findViewById(R.id.button_signup);

        FirebaseDatabase.getInstance( "https://evcharging-45071-default-rtdb.asia-southeast1.firebasedatabase.app");

        btnSignup.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                String email = enterEmail.getText().toString();
                String pass = password.getText().toString();
                String fName = firstName.getText().toString();
                String lName = lastName.getText().toString();
                String mobile = mobileNumber.getText().toString();

                if (email.isEmpty() || pass.isEmpty() || fName.isEmpty() || lName.isEmpty() || mobile.isEmpty()) {
                    Toast.makeText(Signup.this, "Please fill in all fields", Toast.LENGTH_SHORT).show();
                } else {
                    signUpWithEmailAndPassword(email, pass, fName, lName, mobile);
                }
            }
        });
    }

    private void signUpWithEmailAndPassword(final String email, final String password, final String fName, final String lName, final String mobile) {
        mAuth.createUserWithEmailAndPassword(email, password)
                .addOnCompleteListener(this, new OnCompleteListener<AuthResult>() {
                    @Override
                    public void onComplete(@NonNull Task<AuthResult> task) {
                        if (task.isSuccessful()) {
                            // Registration successful
                            Toast.makeText(Signup.this, "Registration Successful", Toast.LENGTH_SHORT).show();

                            // Get the unique user ID generated by Firebase
                            final String userId = Objects.requireNonNull(mAuth.getCurrentUser()).getUid();

                            // Create a User object with the user ID, first name, last name, and mobile number
                            User user = new User(userId, fName, lName, mobile);

                            // Save the user object to the database using the unique user ID
                            DatabaseReference usersRef = FirebaseDatabase.getInstance().getReference("users");
                            usersRef.child(userId).setValue(user);

                            // Proceed to the next activity or perform any other actions
                        } else {
                            // Registration failed
                            Toast.makeText(Signup.this, "Registration failed.", Toast.LENGTH_SHORT).show();
                        }
                    }
                });
    }
}
